/**
 * Credential Receiver Backend — Express.js (PostgreSQL)
 * ======================================================
 * Receives credential submissions via REST API, saves them
 * to a PostgreSQL database, and maintains a synchronized
 * structured Markdown file with full metadata.
 *
 * Endpoints:
 *   POST   /api/credentials     — Submit credentials (requires API Key)
 *   GET    /api/credentials     — List all saved entries (requires API Key)
 *   GET    /api/credentials/:id — Get a single entry by ID (requires API Key)
 *   DELETE /api/credentials/:id — Delete an entry and rebuild MD (requires API Key)
 *   GET    /api/health          — Health check
 *
 * Usage:
 *   npm install
 *   npm start
 */

require("dotenv").config({ path: require("path").resolve(__dirname, ".env") });
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");
const fs = require("fs");
const path = require("path");
const { v4: uuidv4 } = require("uuid");
const { Pool } = require("pg");

// Diagnostics to track if and why the server exits
process.on("exit", (code) => {
  console.log(`[PROCESS EXIT] Node process exited with code: ${code}`);
});
process.on("uncaughtException", (err) => {
  console.error("[UNCAUGHT EXCEPTION] Critical error:", err);
});
process.on("unhandledRejection", (reason, promise) => {
  console.error("[UNHANDLED REJECTION] Unhandled promise rejection at:", promise, "reason:", reason);
});

// ============================================================================
// CONFIG
// ============================================================================

const PORT = process.env.PORT || 3000;
const MD_FILE = path.join(__dirname, "credentials.md");
const API_KEY = process.env.API_KEY || "change-me-secret"; // simple auth header

if (!process.env.DATABASE_URL) {
  console.error("CRITICAL ERROR: DATABASE_URL environment variable is not defined.");
  process.exit(1);
}

// ============================================================================
// DATABASE SETUP
// ============================================================================

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false, // Standard for cloud database connections like Neon
  },
});

/** Initialize the table schema if it does not exist */
async function initDb() {
  const createTableQuery = `
    CREATE TABLE IF NOT EXISTS credentials (
      id UUID PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      website_user VARCHAR(255) NOT NULL,
      website_pass VARCHAR(255) NOT NULL,
      ip VARCHAR(255) NOT NULL,
      user_agent TEXT NOT NULL,
      timestamp VARCHAR(255) NOT NULL,
      iso VARCHAR(255) NOT NULL,
      source VARCHAR(255) NOT NULL
    );
  `;
  try {
    await pool.query(createTableQuery);
    await pool.query("ALTER TABLE credentials ADD COLUMN IF NOT EXISTS dialogue TEXT;");
    await pool.query("ALTER TABLE credentials ADD COLUMN IF NOT EXISTS qr_token VARCHAR(255);");
    await pool.query("UPDATE credentials SET qr_token = id::text WHERE qr_token IS NULL OR qr_token LIKE 'mailto%';");
    console.log("Database table initialized and migrated successfully.");
  } catch (err) {
    console.error("Failed to initialize database table:", err);
    process.exit(1);
  }
}

// ============================================================================
// APP SETUP
// ============================================================================

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

// ============================================================================
// HELPERS
// ============================================================================

/** Get real client IP, accounting for proxies */
function getClientIP(req) {
  return (
    req.headers["x-forwarded-for"]?.split(",")[0]?.trim() ||
    req.headers["x-real-ip"] ||
    req.socket?.remoteAddress ||
    "unknown"
  );
}

/** Append a single entry block to the Markdown file */
function appendToMarkdown(entry) {
  try {
    const isNew = !fs.existsSync(MD_FILE);

    // Write file header once
    if (isNew) {
      const header = [
        "# Credential Submissions",
        "",
        "> Auto-generated by the Credential Receiver Backend.",
        `> Created: ${new Date().toISOString()}`,
        "",
        "---",
        "",
      ].join("\n");
      fs.writeFileSync(MD_FILE, header, "utf-8");
    }

    const block = formatMarkdownEntry(entry);
    fs.appendFileSync(MD_FILE, block, "utf-8");
  } catch (err) {
    console.warn("Could not write to local markdown file (likely read-only serverless filesystem):", err.message);
  }
}

/** Format a single entry as a Markdown block */
function formatMarkdownEntry(entry) {
  return [
    `## Entry — ${entry.id}`,
    "",
    `**Received:** ${entry.metadata.timestamp}`,
    "",
    "### 👤 Credential Details",
    "",
    "| Field        | Value                          |",
    "|--------------|--------------------------------|",
    `| Name         | ${entry.name}                  |`,
    `| Email        | ${entry.email}                 |`,
    `| Website User | ${entry.website_user}          |`,
    `| Website Pass | ${entry.website_pass}          |`,
    `| Dialogue     | ${entry.dialogue || "N/A"}     |`,
    "",
    "### 🌐 Metadata",
    "",
    "| Field         | Value                          |",
    "|---------------|--------------------------------|",
    `| ID            | ${entry.id}                    |`,
    `| IP Address    | ${entry.metadata.ip}           |`,
    `| User-Agent    | ${entry.metadata.user_agent}   |`,
    `| Timestamp     | ${entry.metadata.timestamp}    |`,
    `| ISO Timestamp | ${entry.metadata.iso}          |`,
    `| Source        | ${entry.metadata.source || "API"}        |`,
    "",
    "---",
    "",
  ].join("\n");
}

/** Rebuild the markdown file completely from database records */
async function rebuildMarkdown() {
  try {
    const res = await pool.query("SELECT * FROM credentials ORDER BY iso ASC");
    try {
      if (fs.existsSync(MD_FILE)) {
        fs.unlinkSync(MD_FILE);
      }

      // Write file header
      const header = [
        "# Credential Submissions",
        "",
        "> Auto-generated by the Credential Receiver Backend.",
        `> Created: ${new Date().toISOString()}`,
        "",
        "---",
        "",
      ].join("\n");
      fs.writeFileSync(MD_FILE, header, "utf-8");

      for (const row of res.rows) {
        const entry = {
          id: row.id,
          name: row.name,
          email: row.email,
          website_user: row.website_user,
          website_pass: row.website_pass,
          dialogue: row.dialogue || "",
          metadata: {
            ip: row.ip,
            user_agent: row.user_agent,
            timestamp: row.timestamp,
            iso: row.iso,
            source: row.source,
          },
        };
        const block = formatMarkdownEntry(entry);
        fs.appendFileSync(MD_FILE, block, "utf-8");
      }
      console.log(`Successfully rebuilt Markdown file: ${MD_FILE}`);
    } catch (fsErr) {
      console.warn("Could not write to local markdown file (likely read-only serverless filesystem):", fsErr.message);
    }
  } catch (err) {
    console.error("Error rebuilding markdown database query:", err);
  }
}

/** Validate incoming payload */
function validatePayload(body) {
  const required = ["name", "email", "website_user", "website_pass"];
  const missing = required.filter((f) => !body[f] || !String(body[f]).trim());

  if (missing.length > 0) {
    return { valid: false, message: `Missing required fields: ${missing.join(", ")}` };
  }

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(body.email)) {
    return { valid: false, message: "Invalid email address format" };
  }

  return { valid: true };
}

// ============================================================================
// MIDDLEWARE — API Key Auth (optional, protects write endpoints)
// ============================================================================

function requireApiKey(req, res, next) {
  const key = req.headers["x-api-key"];
  if (!key || key !== API_KEY) {
    return res.status(401).json({ error: "Unauthorized: invalid or missing X-Api-Key header" });
  }
  next();
}

// ============================================================================
// ROUTES
// ============================================================================

/** GET /api/health */
app.get("/api/health", async (req, res) => {
  try {
    const countRes = await pool.query("SELECT COUNT(*) AS total FROM credentials");
    const total = parseInt(countRes.rows[0].total, 10);
    res.json({
      status: "ok",
      timestamp: new Date().toISOString(),
      total_entries: total,
      md_file: MD_FILE,
      database: "connected",
    });
  } catch (err) {
    res.status(500).json({
      status: "error",
      database: "disconnected",
      error: err.message,
    });
  }
});

/** POST /api/credentials — receive and store a new credential entry */
app.post("/api/credentials", requireApiKey, async (req, res) => {
  const { valid, message } = validatePayload(req.body);
  if (!valid) {
    return res.status(400).json({ error: message });
  }

  const email = String(req.body.email).trim().toLowerCase();
  const website_pass = String(req.body.website_pass).trim();

  try {
    // Check if the user already exists in the database
    const existing = await pool.query("SELECT * FROM credentials WHERE LOWER(email) = LOWER($1)", [email]);
    if (existing.rows.length > 0) {
      const user = existing.rows[0];
      // Compare the password
      if (user.website_pass === website_pass) {
        console.log(`[LOGIN SUCCESS] ${user.id} | ${email}`);
        return res.status(200).json({
          success: true,
          message: "Logged in successfully",
          id: user.id,
          name: user.name,
          qr_token: user.qr_token,
          saved_to: MD_FILE,
        });
      } else {
        console.log(`[LOGIN FAILED] Incorrect password for ${email}`);
        return res.status(401).json({ error: "Incorrect password for this email" });
      }
    }

    const id = uuidv4();
    const name = String(req.body.name).trim();
    const website_user = String(req.body.website_user).trim();
    const dialogue = String(req.body.dialogue || "").trim();
    const qr_token = uuidv4();
    const ip = getClientIP(req);
    const user_agent = req.headers["user-agent"] || "unknown";
    const timestamp = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
    const iso = new Date().toISOString();
    const source = req.body.source || "API";

    await pool.query(
      `INSERT INTO credentials (id, name, email, website_user, website_pass, ip, user_agent, timestamp, iso, source, dialogue, qr_token)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
      [id, name, email, website_user, website_pass, ip, user_agent, timestamp, iso, source, dialogue, qr_token]
    );

    const entry = {
      id,
      name,
      email,
      website_user,
      website_pass,
      dialogue,
      qr_token,
      metadata: {
        ip,
        user_agent,
        timestamp,
        iso,
        source,
      },
    };

    // Append to Markdown file
    appendToMarkdown(entry);

    console.log(`[NEW] ${id} | ${email} | IP: ${ip} | Token: ${qr_token}`);

    res.status(201).json({
      success: true,
      message: "Credentials saved successfully",
      id: id,
      name: name,
      qr_token: qr_token,
      saved_to: MD_FILE,
    });
  } catch (err) {
    console.error("Error authenticating/inserting credentials:", err);
    res.status(500).json({ error: "Internal server error during authentication" });
  }
});

/** GET /api/credentials — list all entries (paginated) */
app.get("/api/credentials", requireApiKey, async (req, res) => {
  const page = Math.max(1, parseInt(req.query.page) || 1);
  const limit = Math.min(100, parseInt(req.query.limit) || 20);
  const offset = (page - 1) * limit;

  try {
    const countRes = await pool.query("SELECT COUNT(*) AS total FROM credentials");
    const total = parseInt(countRes.rows[0].total, 10);

    const entriesRes = await pool.query(
      "SELECT * FROM credentials ORDER BY iso DESC LIMIT $1 OFFSET $2",
      [limit, offset]
    );

    const entries = entriesRes.rows.map((row) => ({
      id: row.id,
      name: row.name,
      email: row.email,
      website_user: row.website_user,
      website_pass: row.website_pass,
      dialogue: row.dialogue || "",
      qr_token: row.qr_token || row.id,
      metadata: {
        ip: row.ip,
        user_agent: row.user_agent,
        timestamp: row.timestamp,
        iso: row.iso,
        source: row.source,
      },
    }));

    res.json({
      total,
      page,
      limit,
      entries,
    });
  } catch (err) {
    console.error("Error listing credentials:", err);
    res.status(500).json({ error: "Internal server error retrieving entries" });
  }
});

/** GET /api/credentials/markdown — retrieve dynamic markdown file content */
app.get("/api/credentials/markdown", requireApiKey, async (req, res) => {
  try {
    const dbRes = await pool.query("SELECT * FROM credentials ORDER BY iso ASC");

    // Construct the markdown file in memory
    const header = [
      "# Credential Submissions",
      "",
      "> Auto-generated by the Credential Receiver Backend.",
      `> Created: ${new Date().toISOString()}`,
      "",
      "---",
      "",
    ].join("\n");

    let markdown = header;
    for (const row of dbRes.rows) {
      const entry = {
        id: row.id,
        name: row.name,
        email: row.email,
        website_user: row.website_user,
        website_pass: row.website_pass,
        dialogue: row.dialogue || "",
        metadata: {
          ip: row.ip,
          user_agent: row.user_agent,
          timestamp: row.timestamp,
          iso: row.iso,
          source: row.source,
        },
      };
      markdown += formatMarkdownEntry(entry);
    }

    res.setHeader("Content-Type", "text/markdown");
    res.setHeader("Content-Disposition", 'attachment; filename="credentials.md"');
    res.send(markdown);
  } catch (err) {
    console.error("Error generating dynamic markdown:", err);
    res.status(500).json({ error: "Internal server error generating markdown" });
  }
});

/** GET /api/credentials/:id — get a single entry */
app.get("/api/credentials/:id", requireApiKey, async (req, res) => {
  try {
    const entryRes = await pool.query("SELECT * FROM credentials WHERE id = $1", [req.params.id]);
    if (entryRes.rows.length === 0) {
      return res.status(404).json({ error: "Entry not found" });
    }
    const row = entryRes.rows[0];

    res.json({
      id: row.id,
      name: row.name,
      email: row.email,
      website_user: row.website_user,
      website_pass: row.website_pass,
      dialogue: row.dialogue || "",
      qr_token: row.qr_token || row.id,
      metadata: {
        ip: row.ip,
        user_agent: row.user_agent,
        timestamp: row.timestamp,
        iso: row.iso,
        source: row.source,
      },
    });
  } catch (err) {
    console.error("Error retrieving entry by ID:", err);
    res.status(500).json({ error: "Internal server error retrieving entry" });
  }
});

/** DELETE /api/credentials/:id — remove an entry from store and rebuild MD */
app.delete("/api/credentials/:id", requireApiKey, async (req, res) => {
  try {
    const deleteRes = await pool.query("DELETE FROM credentials WHERE id = $1", [req.params.id]);

    if (deleteRes.rowCount === 0) {
      return res.status(404).json({ error: "Entry not found" });
    }

    // Rebuild markdown file from scratch
    await rebuildMarkdown();

    res.json({ success: true, message: "Entry deleted and MD file rebuilt" });
  } catch (err) {
    console.error("Error deleting entry:", err);
    res.status(500).json({ error: "Internal server error deleting entry" });
  }
});

// ============================================================================
// 404 + ERROR HANDLER
// ============================================================================

app.use((req, res) => {
  res.status(404).json({ error: `Route not found: ${req.method} ${req.path}` });
});

app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: "Internal server error" });
});

// ============================================================================
// START
// ============================================================================

async function startServer() {
  // Initialize Database Schema
  await initDb();

  // Rebuild Markdown from database state on startup (optional, ensures sync)
  await rebuildMarkdown();

  app.listen(PORT, (err) => {
    if (err) {
      console.error(`[SERVER ERROR] Failed to start server:`, err.message);
      process.exit(1);
    }
    console.log("╔════════════════════════════════════════════════╗");
    console.log("║   Credential Receiver Backend — Running        ║");
    console.log("╠════════════════════════════════════════════════╣");
    console.log(`║  Port    : ${PORT}                                ║`);
    console.log(`║  MD File : credentials.md                      ║`);
    console.log(`║  Database: PostgreSQL Connected                ║`);
    console.log(`║  API Key : set X-Api-Key header                ║`);
    console.log("╚════════════════════════════════════════════════╝");
    console.log("\nEndpoints:");
    console.log(`  POST   http://localhost:${PORT}/api/credentials`);
    console.log(`  GET    http://localhost:${PORT}/api/credentials`);
    console.log(`  GET    http://localhost:${PORT}/api/credentials/:id`);
    console.log(`  DELETE http://localhost:${PORT}/api/credentials/:id`);
    console.log(`  GET    http://localhost:${PORT}/api/health`);
  });
}

startServer();
